export const ALL_LIST_ITEMS = 'ALL_LIST_ITEMS'
export const ADD_LIST_ITEM = 'ADD_LIST_ITEM'
export const EDIT_LIST_ITEM = 'EDIT_LIST_ITEM'
export const DELETE_LIST_ITEM = 'DELETE_LIST_ITEM'

export const CHANGE_ITEM_STATUS ='CHANGE_ITEM_STATUS'
export const TRY_DELETE_ITEM ='TRY_DELETE_ITEM'
export const QUIT_DELETE_ITEM ='QUIT_DELETE_ITEM'
